import type { Job } from "@/lib/types";

// Temporary mock data — will be replaced with Supabase queries
export const mockJobs: Job[] = [
  {
    id: "1",
    employer_id: "emp1",
    title: "Barista",
    company: "The Bean Scene",
    location: "Centrum",
    lat: null,
    lng: null,
    distance: "1.2 km",
    pay: 18,
    pay_unit: "/ hod",
    tips: true,
    date: "zítra",
    time_start: "7:00",
    time_end: "13:00",
    duration: "6 hod",
    description: "Hledáme milého a spolehlivého baristu na ranní směny.",
    requirements: ["Zájem o kávu", "Spolehlivost", "Příjemné vystupování"],
    tags: ["Žádané pozice", "Bez zkušeností"],
    image_url: "https://ggrhecslgdflloszjkwl.supabase.co/storage/v1/object/public/user-assets/MHIY6QacKaF/components/FU7SALGOTUw.png",
    status: "active",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    employer_id: "emp2",
    title: "Pomocník v kuchyni",
    company: "Burger Palace",
    location: "Nové Město",
    lat: null,
    lng: null,
    distance: "2.1 km",
    pay: 16,
    pay_unit: "/ hod",
    tips: false,
    date: "dnes",
    time_start: "17:00",
    time_end: "22:00",
    duration: "5 hod",
    description: "Pomoc v kuchyni v rušném burgerovém podniku.",
    requirements: ["Zkušenosti v kuchyni výhodou", "Rychlost", "Čistota"],
    tags: ["Pohodové"],
    image_url: "https://images.unsplash.com/photo-1568901346405-7dcbbdee2f4c?w=400",
    status: "active",
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    employer_id: "emp3",
    title: "Číšník",
    company: "City Cafe",
    location: "Staré Město",
    lat: null,
    lng: null,
    distance: "0.8 km",
    pay: 17,
    pay_unit: "/ hod",
    tips: true,
    date: "zítra",
    time_start: "12:00",
    time_end: "18:00",
    duration: "6 hod",
    description: "Obsluha hostů v moderní kavárně.",
    requirements: ["Zkušenosti s obsluhou", "Angličtina výhodou", "Smích"],
    tags: ["Flexibilní"],
    image_url: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400",
    status: "active",
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    employer_id: "emp4",
    title: "Řidič rozvozu",
    company: "Pizza Express",
    location: "Královské Vinohrady",
    lat: null,
    lng: null,
    distance: "3.5 km",
    pay: 15,
    pay_unit: "/ hod",
    tips: true,
    date: "dnes",
    time_start: "18:00",
    time_end: "23:00",
    duration: "5 hod",
    description: "Rozvoz jídla na skútru.",
    requirements: ["Řidičský průkaz", "Přehled Prahy", "Spolehlivost"],
    tags: ["Žádané pozice", "Flexibilní"],
    image_url: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400",
    status: "active",
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    employer_id: "emp5",
    title: "Sous Chef",
    company: "Sushi Master",
    location: "Karlín",
    lat: null,
    lng: null,
    distance: "1.8 km",
    pay: 22,
    pay_unit: "/ hod",
    tips: true,
    date: "zítra",
    time_start: "11:00",
    time_end: "22:00",
    duration: "11 hod",
    description: "Pomoc šéfkuchaři v moderní sushi restauraci.",
    requirements: ["Zkušenosti s japonskou kuchyní", "Preciznost", "Týmový duch"],
    tags: ["Žádané pozice", "Zkušenosti vyžadovány"],
    image_url: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400",
    status: "active",
    created_at: new Date().toISOString(),
  },
];
